"""
Professional AI - AI Providers Configuration
Central registry of all supported AI providers with metadata:
model names, costs per 1K tokens, rate limits, capabilities, and API URLs.
This file is read by the AI router, health monitor, and dashboard.
"""

AI_PROVIDERS_CONFIG = {
    "openai": {
        "name": "OpenAI",
        "env_key": "OPENAI_API_KEY",
        "env_keys": "OPENAI_KEYS",
        "base_url": "https://api.openai.com/v1",
        "chat_model": "gpt-4o-mini",
        "code_model": "gpt-4o",
        "cost_per_1k_input": 0.00015,
        "cost_per_1k_output": 0.0006,
        "rate_limit_rpm": 500,
        "max_tokens": 128000,
        "supports_streaming": True,
        "supports_vision": True,
        "supports_code": True,
        "api_format": "openai",
    },
    "anthropic": {
        "name": "Anthropic Claude",
        "env_key": "ANTHROPIC_API_KEY",
        "env_keys": "ANTHROPIC_KEYS",
        "base_url": "https://api.anthropic.com/v1",
        "chat_model": "claude-sonnet-4-20250514",
        "code_model": "claude-sonnet-4-20250514",
        "cost_per_1k_input": 0.003,
        "cost_per_1k_output": 0.015,
        "rate_limit_rpm": 1000,
        "max_tokens": 200000,
        "supports_streaming": True,
        "supports_vision": True,
        "supports_code": True,
        "api_format": "anthropic",
    },
    "gemini": {
        "name": "Google Gemini",
        "env_key": "GEMINI_API_KEY",
        "env_keys": "GEMINI_KEYS",
        "base_url": "https://generativelanguage.googleapis.com/v1beta",
        "chat_model": "gemini-2.0-flash",
        "code_model": "gemini-2.0-flash",
        "cost_per_1k_input": 0.000075,
        "cost_per_1k_output": 0.0003,
        "rate_limit_rpm": 60,
        "max_tokens": 1048576,
        "supports_streaming": True,
        "supports_vision": True,
        "supports_code": True,
        "api_format": "gemini",
    },
    "groq": {
        "name": "Groq",
        "env_key": "GROQ_API_KEY",
        "env_keys": "GROQ_KEYS",
        "base_url": "https://api.groq.com/openai/v1",
        "chat_model": "llama-3.3-70b-versatile",
        "code_model": "llama-3.3-70b-versatile",
        "cost_per_1k_input": 0.00059,
        "cost_per_1k_output": 0.00079,
        "rate_limit_rpm": 30,
        "max_tokens": 32768,
        "supports_streaming": True,
        "supports_vision": False,
        "supports_code": True,
        "api_format": "openai",
    },
    "deepseek": {
        "name": "DeepSeek",
        "env_key": "DEEPSEEK_API_KEY",
        "env_keys": "DEEPSEEK_KEYS",
        "base_url": "https://api.deepseek.com/v1",
        "chat_model": "deepseek-chat",
        "code_model": "deepseek-reasoner",
        "cost_per_1k_input": 0.00014,
        "cost_per_1k_output": 0.00028,
        "rate_limit_rpm": 60,
        "max_tokens": 65536,
        "supports_streaming": True,
        "supports_vision": False,
        "supports_code": True,
        "api_format": "openai",
    },
    "mistral": {
        "name": "Mistral AI",
        "env_key": "MISTRAL_API_KEY",
        "env_keys": "MISTRAL_KEYS",
        "base_url": "https://api.mistral.ai/v1",
        "chat_model": "mistral-small-latest",
        "code_model": "codestral-latest",
        "cost_per_1k_input": 0.0002,
        "cost_per_1k_output": 0.0006,
        "rate_limit_rpm": 60,
        "max_tokens": 32768,
        "supports_streaming": True,
        "supports_vision": False,
        "supports_code": True,
        "api_format": "openai",
    },
    "openrouter": {
        "name": "OpenRouter",
        "env_key": "OPENROUTER_API_KEY",
        "env_keys": "OPENROUTER_KEYS",
        "base_url": "https://openrouter.ai/api/v1",
        "chat_model": "deepseek/deepseek-chat",
        "code_model": "qwen/qwen2.5-coder-32b-instruct",
        "cost_per_1k_input": 0.0001,
        "cost_per_1k_output": 0.0003,
        "rate_limit_rpm": 200,
        "max_tokens": 65536,
        "supports_streaming": True,
        "supports_vision": True,
        "supports_code": True,
        "api_format": "openai",
    },
    "together": {
        "name": "Together AI",
        "env_key": "TOGETHER_API_KEY",
        "env_keys": "TOGETHER_KEYS",
        "base_url": "https://api.together.xyz/v1",
        "chat_model": "meta-llama/Llama-3.3-70B-Instruct-Turbo",
        "code_model": "deepseek-ai/DeepSeek-V3",
        "cost_per_1k_input": 0.0002,
        "cost_per_1k_output": 0.0002,
        "rate_limit_rpm": 60,
        "max_tokens": 8192,
        "supports_streaming": True,
        "supports_vision": False,
        "supports_code": True,
        "api_format": "openai",
    },
    "xai": {
        "name": "xAI Grok",
        "env_key": "XAI_API_KEY",
        "env_keys": "XAI_KEYS",
        "base_url": "https://api.x.ai/v1",
        "chat_model": "grok-beta",
        "code_model": "grok-beta",
        "cost_per_1k_input": 0.0005,
        "cost_per_1k_output": 0.0015,
        "rate_limit_rpm": 60,
        "max_tokens": 131072,
        "supports_streaming": True,
        "supports_vision": True,
        "supports_code": True,
        "api_format": "openai",
    },
    "stability": {
        "name": "Stability AI",
        "env_key": "STABILITY_API_KEY",
        "env_keys": "STABILITY_KEYS",
        "base_url": "https://api.stability.ai/v1",
        "chat_model": "stable-diffusion-xl",
        "code_model": "stable-diffusion-xl",
        "cost_per_1k_input": 0.002,
        "cost_per_1k_output": 0.002,
        "rate_limit_rpm": 10,
        "max_tokens": 4096,
        "supports_streaming": False,
        "supports_vision": False,
        "supports_code": False,
        "api_format": "stability",
    },
}

# Priority order for provider failover (fastest / cheapest first)
DEFAULT_PROVIDER_ORDER = [
    "openai",
    "anthropic",
    "gemini",
    "groq",
    "deepseek",
    "mistral",
    "openrouter",
    "together",
    "xai",
    "stability",
]

# Provider features mapping
PROVIDER_FEATURES = {
    "openai": ["chat", "code", "vision", "streaming", "function_calling"],
    "anthropic": ["chat", "code", "vision", "streaming"],
    "gemini": ["chat", "code", "vision", "streaming"],
    "groq": ["chat", "code", "streaming"],
    "deepseek": ["chat", "code", "streaming"],
    "mistral": ["chat", "code", "streaming"],
    "openrouter": ["chat", "code", "vision", "streaming"],
    "together": ["chat", "code", "streaming"],
    "xai": ["chat", "code", "vision", "streaming"],
    "stability": ["image"],
}
