declare module 'lucide-react' {
  import { SVGProps } from 'react'

  export interface LucideProps extends SVGProps<SVGSVGElement> {
    size?: number | string
    color?: string
    strokeWidth?: number | string
    absoluteStrokeWidth?: boolean
  }

  export type LucideIcon = (props: LucideProps) => JSX.Element

  export const Activity: LucideIcon
  export const AlertTriangle: LucideIcon
  export const AlignJustify: LucideIcon
  export const ArrowDown: LucideIcon
  export const ArrowLeft: LucideIcon
  export const ArrowRight: LucideIcon
  export const ArrowUp: LucideIcon
  export const AtSign: LucideIcon
  export const Award: LucideIcon
  export const Badge: LucideIcon
  export const Balloon: LucideIcon
  export const Battery: LucideIcon
  export const Bell: LucideIcon
  export const Bookmark: LucideIcon
  export const Briefcase: LucideIcon
  export const Camera: LucideIcon
  export const Check: LucideIcon
  export const CheckCircle: LucideIcon
  export const CheckCircle2: LucideIcon
  export const ChevronDown: LucideIcon
  export const ChevronLeft: LucideIcon
  export const ChevronRight: LucideIcon
  export const ChevronUp: LucideIcon
  export const CircleStop: LucideIcon
  export const Clipboard: LucideIcon
  export const Cloud: LucideIcon
  export const Code: LucideIcon
  export const Code2: LucideIcon
  export const Command: LucideIcon
  export const Copy: LucideIcon
  export const CreditCard: LucideIcon
  export const Crown: LucideIcon
  export const Cpu: LucideIcon
  export const Database: LucideIcon
  export const DollarSign: LucideIcon
  export const Download: LucideIcon
  export const Droplet: LucideIcon
  export const Edit: LucideIcon
  export const Edit3: LucideIcon
  export const ExternalLink: LucideIcon
  export const Eye: LucideIcon
  export const File: LucideIcon
  export const FileText: LucideIcon
  export const FileType2: LucideIcon
  export const FileSpreadsheet: LucideIcon
  export const FileImage: LucideIcon
  export const Film: LucideIcon
  export const Flag: LucideIcon
  export const Flame: LucideIcon
  export const Folder: LucideIcon
  export const FolderOpen: LucideIcon
  export const Gamepad: LucideIcon
  export const Gift: LucideIcon
  export const GitCompare: LucideIcon
  export const Globe: LucideIcon
  export const GraduationCap: LucideIcon
  export const HardDrive: LucideIcon
  export const Hash: LucideIcon
  export const Heart: LucideIcon
  export const HelpCircle: LucideIcon
  export const Home: LucideIcon
  export const Image: LucideIcon
  export const Info: LucideIcon
  export const Inbox: LucideIcon
  export const Keyboard: LucideIcon
  export const Laptop: LucideIcon
  export const Lightbulb: LucideIcon
  export const Link: LucideIcon
  export const Link2: LucideIcon
  export const List: LucideIcon
  export const ListChecks: LucideIcon
  export const ListFilter: LucideIcon
  export const ListPlus: LucideIcon
  export const ListX: LucideIcon
  export const Lock: LucideIcon
  export const Mail: LucideIcon
  export const Map: LucideIcon
  export const MapPin: LucideIcon
  export const Maximize: LucideIcon
  export const Maximize2: LucideIcon
  export const Menu: LucideIcon
  export const MessageCircle: LucideIcon
  export const MessageSquare: LucideIcon
  export const Mic: LucideIcon
  export const MicOff: LucideIcon
  export const Minimize: LucideIcon
  export const Minimize2: LucideIcon
  export const Monitor: LucideIcon
  export const Moon: LucideIcon
  export const MoreHorizontal: LucideIcon
  export const MoreVertical: LucideIcon
  export const Mouse: LucideIcon
  export const Music: LucideIcon
  export const Pause: LucideIcon
  export const Pen: LucideIcon
  export const Phone: LucideIcon
  export const Play: LucideIcon
  export const Plus: LucideIcon
  export const Presentation: LucideIcon
  export const Printer: LucideIcon
  export const Radio: LucideIcon
  export const RefreshCw: LucideIcon
  export const Remove: LucideIcon
  export const RotateCcw: LucideIcon
  export const RotateCw: LucideIcon
  export const Save: LucideIcon
  export const Scan: LucideIcon
  export const Scissors: LucideIcon
  export const Search: LucideIcon
  export const Send: LucideIcon
  export const Newspaper: LucideIcon
  export const Server: LucideIcon
  export const Settings: LucideIcon
  export const Share: LucideIcon
  export const Shield: LucideIcon
  export const ShieldCheck: LucideIcon
  export const Signal: LucideIcon
  export const Slash: LucideIcon
  export const Smartphone: LucideIcon
  export const Snowflake: LucideIcon
  export const Speaker: LucideIcon
  export const Square: LucideIcon
  export const Star: LucideIcon
  export const StopCircle: LucideIcon
  export const Sun: LucideIcon
  export const Tablet: LucideIcon
  export const Tag: LucideIcon
  export const Terminal: LucideIcon
  export const Text: LucideIcon
  export const Thermometer: LucideIcon
  export const Ticket: LucideIcon
  export const Train: LucideIcon
  export const Trash: LucideIcon
  export const Trash2: LucideIcon
  export const TrendingUp: LucideIcon
  export const Triangle: LucideIcon
  export const Truck: LucideIcon
  export const Tv: LucideIcon
  export const Type: LucideIcon
  export const Umbrella: LucideIcon
  export const Unlink: LucideIcon
  export const Upload: LucideIcon
  export const User: LucideIcon
  export const UserCheck: LucideIcon
  export const UserCircle: LucideIcon
  export const UserMinus: LucideIcon
  export const UserPlus: LucideIcon
  export const Users: LucideIcon
  export const Video: LucideIcon
  export const VideoIcon: LucideIcon
  export const Voicemail: LucideIcon
  export const Volume: LucideIcon
  export const Volume1: LucideIcon
  export const Volume2: LucideIcon
  export const VolumeX: LucideIcon
  export const Wand: LucideIcon
  export const Wand2: LucideIcon
  export const WandSparkles: LucideIcon
  export const Watch: LucideIcon
  export const Wifi: LucideIcon
  export const Wind: LucideIcon
  export const X: LucideIcon
  export const XCircle: LucideIcon
  export const Zap: LucideIcon
  export const Bot: LucideIcon
  export const Loader2: LucideIcon
  export const Sparkles: LucideIcon
  export const Clapperboard: LucideIcon
  export const Scissors: LucideIcon
  export const Sliders: LucideIcon
  export const Palette: LucideIcon
  export const Crop: LucideIcon
  export const MonitorPlay: LucideIcon
  export const BadgeCheck: LucideIcon
  export const Languages: LucideIcon
  export const ChevronDown: LucideIcon
  export const WandSparkles: LucideIcon
  export const LogOut: LucideIcon

  export default LucideReact
  function LucideReact(props: LucideProps): JSX.Element
}
